[theme]

# Primary accent for interactive elements
primaryColor = '#cc4452'

# Background color for the main content area
backgroundColor = '#e7aeb4'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '1c1c1c'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"